# happy path
http://localhost:8080
POST /player
{
    "command" : "pause",
    "value" : "null"
}

http://localhost:8080
POST /player
{
    "command" : "pause"
}

# happy path
http://localhost:8080
POST /player
{
    "command" : "resume"
}

http://localhost:8080
POST /player
{
    "command" : "stop"
}

# Error case 
http://localhost:8080
POST /player
{
    "command" : "something",
    "value" : "null"
}

# returns 400
http://localhost:8080
POST /player
{
    "command" : "play"
}

# plays target
http://localhost:8080
POST /player
{
    "command" : "play",
    "value" : "https://www.youtube.com/watch?v=MbVON7Oa0qI"
}

http://localhost:8080
POST /player
{
    "command" : "status",
    "value" : "https://www.youtube.com/watch?v=MbVON7Oa0qI"
}

# VOLUME TESTS
http://localhost:8080
GET /volume


# set volume
http://localhost:8080
POST /volume
{"value":"0"}


# set property
http://localhost:8080
POST /player/property
{"property": "time-pos" , "value":"70.267"}


# get property
http://localhost:8080
POST /player/property
{"property": "time-pos" }

# get property
http://localhost:8080
POST /player/property
{"property": "duration" }


http://localhost:8080
GET /favourites

http://localhost:8080
POST /favourites/search
{
    "search_term" : "Terra X",
    "offset" : 0
}

http://localhost:8080
GET /series/detail/67198

http://localhost:8080
GET /series

http://localhost:8080
GET /episodes

http://localhost:8080
GET /episodes/1412/6

http://localhost:8080
GET /episodes/1412/6/1

http://localhost:8080
GET /movies

http://localhost:8080
GET /movies/1234


http://localhost:8080
POST /movies/search-movie
{
    "term" : "Spione undercover eine wilde"
}

http://localhost:8080
GET /library/scan

http://localhost:8080
POST /library/ignore
{"tmdb_id":69088,
"path" : ""
}

# bad path
http://localhost:8080
POST /library/add
{
    "tmdb_id":1403,
    "path" : "/home/maren/Downloads/complete/Marvel's Agents of S.H.I.E.L.D",
    "schema" : "serie"
}

# happy path
http://localhost:8080
POST /library/add
{
    "tmdb_id":1403,
    "path" : "/home/maren/Downloads/complete/Marvel's Agents of S.H.I.E.L.D",
    "schema" : "serie"
}


http://localhost:8080
POST /library/add
{
    "tmdb_id":431693,
    "path" : "/home/maren/Downloads/complete/movies/Black Panther.mkv",
    "schema" : "movie"
}

