http://localhost:9990
GET /

# addd item to playlist 
http://localhost:9990
POST /player/add 
{"value":"asdfasdf","client":"null"}

# Resume
http://localhost:9990
GET /player/resume

# Pause
http://localhost:9990
GET /player/pause

# Pause
http://localhost:9990
GET /player/stop

# Start a video 
http://localhost:9990
POST /player
{"target":"https://www.youtube.com/watch?v=dQw4w9WgXcQ","client":"null"}

# get volume
http://localhost:9990
GET /volume


# set volume
http://localhost:9990
POST /volume
{"client": "null" , "value":"100"}

# get propery
http://localhost:9990
GET /player/propery?target=time-pos

http://localhost:9990
POST /player/propery
{"client": "null" , "value":"100"}

# get scan result
http://localhost:9990
GET /library/scan

http://localhost:9990
POST /player/status
{
"path" : "\"https://www.youtube.com/watch?v=dQw4w9WgXcQ\""
}


http://localhost:9990
POST /player/status
{
"path" : "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
}

http://localhost:9990
POST /player/status
{
"path" : "/assdas/asd"
}


http://localhost:9990
POST /player/status
{
"path" : "/asdas/asd"
}


# Ignore serie
http://localhost:9990
POST /library/ignore
{"tmdb_id":69088,
"path" : ""
}

# add to library
http://localhost:9990
POST /library/add
{
    "tmdb_id":1403,
    "path" : "/home/maren/Downloads/complete/Marvel's Agents of S.H.I.E.L.D"
}


# add to library
http://localhost:9990
GET /series/detail/85948

http://localhost:9990
GET /series

http://localhost:9990
GET /episodes

http://localhost:9990
GET /episodes/1403/7

http://localhost:9990
GET /episodes/1412/6/1


http://localhost:9990
GET /movies

http://localhost:9990
GET /movies/431693


http://localhost:9990
POST /movies/search-movie
{
    "term" : "Spione undercover eine wilde"
}


http://localhost:9990
POST /library/add-movie
{
    "tmdb_id":431693,
    "path" : "/home/maren/Downloads/complete/movies/Spione.undercover.Eine.wilde.Verwandlung.2019.German.720p.BluRay.x264/spione.undercover.eine.wilde.verwandlung.2019.german.720p.bluray.x264-details.mkv"
}


http://localhost:9990
GET /favourites

http://localhost:9990
POST /favourites/search
{
    "search_term" : "Terra X"
}

